### ISSUE TITLE
Support for infinite scrolling?

### ISSUE THREAD

**Issue by vsc-github** [tsuyoshiwada/react-stack-grid#3]
I've decided to use this grid in one of my projects. But a real-life feed would need to load items on the fly. Do you have plans on adding an infinite scroll feature to the grid? How would you go ahead to implement something like that?

**Comment by tsuyoshiwada** [comment]
HI @vsc-github, Thanks for issues.

There is no plan to implement infinite scroll with `react-stack-grid`.
It will be out of support, but [brigade/react-waypoint](https://github.com/brigade/react-waypoint) may be helpful :smiley:

**Comment by VesaVainio** [comment]
A comment on this for the benefit of someone who might still come here. I tried an implementation with react-stack-grid and react-waypoint. In my case the content is mostly images, and I need to have the monitorImagesLoaded as true. While scrolling down, the layout is gradually getting slower and slower, and doing the layout starts taking several seconds with just a few hundred pictures even on a reasonably powerful PC. 

Based on this experience I would advice against this react-stack-grid + react-waypoint combo for implementing infinite scrolling.

It's a shame, as otherwise I think react-stack-grid is really nice. With it getting the layout responsive is much easier than with react-masonry-infinite, and the react-masonry-infinite also has some other problems. That's why I wanted to try react-stack-grid for the infinite scroll, but no luck in my case. A shame.

**Comment by Akshay090** [comment]
If any one's reading this topic the do give a try of https://pinterest.github.io/gestalt/#/Masonry and share the review

**Comment by aboozaid** [comment]
The best solution would be using [masonic](https://github.com/jaredLunde/masonic) based on react-virtualized.
